@host= http://localhost:8080
@publicUser={{host}}/public/v1/user
###

GET {{host}} HTTP/1.1

###
POST {{publicUser}}/login HTTP/1.1
content-type: application/json

  {
    "email": "fatih@gmail.com",
    "password": "123456"
  }

###
GET {{publicUser}}/signout HTTP/1.1

###
POST {{publicUser}}/register HTTP/1.1
content-type: application/json

  {
    "emailVerified": false,
    "phoneNumber": "+11234567862",
    "email": "fatih@gmail.com",
    "password": "123456",
    "displayName": "test",
    "photoURL": "http://www.example.com/12345678/photo.png",
    "disabled": false
  }
###

GET {{publicUser}}/allUsers HTTP/1.1
content-type: application/json

###
GET {{publicUser}}/email/ab@ca.com HTTP/1.1
content-type: application/json

###
POST {{publicUser}}/update/l32i8aPK4LRXvKuZrBjgGfmRmqk1 HTTP/1.1
content-type: application/json

  {
    "displayName": "firebase update"
  }
###
POST {{publicUser}}/delete/l32i8aPK4LRXvKuZrBjgGfmRmqk1 HTTP/1.1
content-type: application/json

###
